[package]
name = "replacetag_sys"
version = "0.1.0"
authors = ["Rasmus KildevÃ¦ld <rasmuskildevaeld@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
bindgen = "0.50"
cc = "^1.0"